config/routes.rb
Rails.application.routes.draw do
  resources :library_subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library_subscription.rb
class LibrarySubscription < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/library_subscriptions_controller.rb
class LibrarySubscriptionsController < ApplicationController
  before_action :set_library_subscription, only: [:show, :edit, :update, :destroy]

  # GET /library_subscriptions
  # GET /library_subscriptions.json
  def index
    @library_subscriptions = LibrarySubscription.all
  end

  # GET /library_subscriptions/1
  # GET /library_subscriptions/1.json
  def show
  end

  # GET /library_subscriptions/new
  def new
    @library_subscription = LibrarySubscription.new
  end

  # GET /library_subscriptions/1/edit
  def edit
  end

  # POST /library_subscriptions
  # POST /library_subscriptions.json
  def create
    @library_subscription = LibrarySubscription.new(library_subscription_params)

    respond_to do |format|
      if @library_subscription.save
        format.html { redirect_to @library_subscription, notice: 'Library subscription was successfully created.' }
        format.json { render :show, status: :created, location: @library_subscription }
      else
        format.html { render :new }
        format.json { render json: @library_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /library_subscriptions/1
  # PATCH/PUT /library_subscriptions/1.json
  def update
    respond_to do |format|
      if @library_subscription.update(library_subscription_params)
        format.html { redirect_to @library_subscription, notice: 'Library subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @library_subscription }
      else
        format.html { render :edit }
        format.json { render json: @library_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /library_subscriptions/1
  # DELETE /library_subscriptions/1.json
  def destroy
    @library_subscription.destroy
    respond_to do |format|
      format.html { redirect_to library_subscriptions_url, notice: 'Library subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library_subscription
      @library_subscription = LibrarySubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_subscription_params
      params.require(:library_subscription).permit(:status, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/library_subscriptions_helper.rb
module LibrarySubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentsapplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/library_subscriptions/_form.html.erb
<%= form_for(library_subscription) do |f| %>
  <% if library_subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library_subscription.errors.count, "error") %> prohibited this library_subscription from being saved:</h2>

      <ul>
      <% library_subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.datetime_select :end_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/library_subscriptions/edit.html.erb
<h1>Editing Library Subscription</h1>

<%= render 'form', library_subscription: @library_subscription %>

<%= link_to 'Show', @library_subscription %> |
<%= link_to 'Back', library_subscriptions_path %>

app/views/library_subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Library Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @library_subscriptions.each do |library_subscription| %>
      <tr>
        <td><%= library_subscription.status %></td>
        <td><%= library_subscription.start_date %></td>
        <td><%= library_subscription.end_date %></td>
        <td><%= link_to 'Show', library_subscription %></td>
        <td><%= link_to 'Edit', edit_library_subscription_path(library_subscription) %></td>
        <td><%= link_to 'Destroy', library_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library Subscription', new_library_subscription_path %>

app/views/library_subscriptions/new.html.erb
<h1>New Library Subscription</h1>

<%= render 'form', library_subscription: @library_subscription %>

<%= link_to 'Back', library_subscriptions_path %>

app/views/library_subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @library_subscription.status %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @library_subscription.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @library_subscription.end_date %>
</p>

<%= link_to 'Edit', edit_library_subscription_path(@library_subscription) %> |
<%= link_to 'Back', library_subscriptions_path %>